### ISSUE TITLE
Google account lost.

### ISSUE THREAD

**Issue by Masumxyz** [KathanP19/HowToHunt#249]
I lost my google account and my youtube channel.
I can't complete Google 2step authentication.
I have registered mobile number.
But I can't get access my account please help me.

**Comment by muslimfrompk** [comment]
Did you try to write and explain to the support?

**Comment by MuhammadWaseem29** [comment]
Subject: Re: [KathanP19/HowToHunt] Google account lost. (Issue #249)

Hello Masumxyz,

Thank you for reaching out. We recommend contacting Google support directly
to address your lost account and YouTube channel issue. They should be able
to assist you with the Google 2-step authentication problem you are facing,
especially since you have a registered mobile number.

Please reach out to Google support at [insert Google support contact
information here] for further assistance with recovering your account.

Best regards,
M Waseem
